frontend/static_vol/js/modules/websocket.js
WebSocketManagerクラスにうっかり生息していたloadGameContentメソッドに引導を渡した
=> Delete unused method

backend/tools/requirements.txt, pong-server/tools/requirements.txt, pong4-server/tools/requirements.txt
現在使用しているdjangoのバグによってadmin画面のPlayerを表示する際にエラーが発生するため、バージョンを4.2に変更します
close  #182
=> Update django to version 4.2

frontend/static_vol/js/components/UserRegister.js, frontend/static_vol/js/components/UserRegisterConfirm.js
input=>confirmに進む時点では空いていたusernameが
その後completeするまでの間に取られてしまった場合、
inputに戻して「This username is already taken.」error表示されるようにしました
=> [SIGN UP]input=>confirmに進んだ後にusername isExistsになる場合のハンドリング

pong-server/game-server/pong/consumers.py
マッチが終了する際にpong-serverのPongConumersクラスのインスタンスは得点情報をAPIを通じて更新しますが、ときどき正常に動作しないことがありました。
頻度が高いのは、トーナメントで同時に複数のゲームが行われ、終了処理が重なる場合でした。
トーナメントでは試合後に結果を表示する関係上、マッチが正常に更新されない限り進行が止まってしまうために問題が発覚しやすかったようです。
調査の結果、実際にはトーナメントかどうかによらず発生することがわかりました。
PongConsumerクラスではどちらかのPlayerが10点（以上）を獲得するとゲーム終了となり、クライアントに結果を通知するとともにbackendのAPIを介して得点をデータベースに反映させます。一方、このクラスのdisconnectが呼ばれることでインスタンスは寿命を迎えます。このタイミングがAPIを叩くタイミングを先行した場合に、得点が反映されないという現象が起きます。
サーバーのCPUリソースに余裕がある場合は間に合うようですが、プロセスやスレッドが立て込んでいる場合にはAPIを叩く前にインスタンスが終わってしまうという挙動になるようです。このため、トーナメントでマッチが同時開催されるなどの場合に問題が発生しやすいと考えられます。
asyncioの並列処理に登録し、その終了をdisconnectで待ちます
コメントに強制的に問題を発生させるコードを記述してありますので試してみてください。sleepすることでpatch_match_to_apiを実行する前にインスタンスが終了します。gatherで待つ今回のPRの方法ならば、sleepしてもタスクを終えるのを確実に待ちます。
※ ベースブランチは#245
=> FIX: exit before patch match API

.env_sample, backend/scandamus/scandamus/settings.py, docker-compose.yml, docker-compose_test.yml, pong-server/game-server/mysite/settings.py, pong4-server/game-server/mysite/settings.py
以下のように設定することでログレベルを変更できます
```
BACKEND_LOG_LEVEL=INFO
PONG_LOG_LEVEL=WARNING
PONG4_LOG_LEVEL=WARNING
```
=> Change log level

backend/scandamus/game/tournament.py
細かい上に動いてもいる(さらにフロント側で防御もしてある)のですが、
値の比較なので`==`にしたいです。
=> [update]文字列比較の演算子をis => ==

frontend/static_vol/js/modules/websocketHandler.js
フレンド削除した際、削除した相手のフレンドリストから自分が消えるようにしました
https://github.com/scandamus/ft_transcendence/issues/279
=> [update]remove frind時にフレンドリスト更新

backend/scandamus/game/match_utils.py
デフォルトアバターのplayerがいるとゲーム開始できなくなっていたのを修正しました
すみません！以前もあった不具合なのですがまだ残っていました
=> [fix]typo in get avatar url

docker-compose.yml, docker-compose_test.yml
=> Replace port to expose

frontend/static_vol/js/modules/websocketHandler.js
`tournament`の型がsrtringで、falseでもtrue判定されていたようです。
実際にsessionStorageに格納される`tournament_id`がnull かどうかで判定するようにしました
=> [fix]tournament match or Not 判定にtournament_idを使用

pong-server/game-server/pong/consumers.py, pong4-server/game-server/pong4/consumers.py
#194 
- sendを失敗した際の例外をハンドル
- jsonデコード失敗のハンドル
- asyncioタスクの例外ハンドル
- ステータスコードを変更
4100: URLにmatch idが含まれていない
4101:  match ID conflict （URLのIDとJWTのIDが異なる）
4102: match data not found（match IDがないもしくはユーザーが異なる）
=> Add exception support for game server

pong4-server/game-server/pong4/consumers.py, pong4-server/game-server/pong4/data_serialize.py
=> Rejoin pong4

pong-server/game-server/pong/consumers.py, pong4-server/game-server/pong4/consumers.py
ゲームサーバーでMatchのPATCH APIを2重に叩くようになってしまったためにトーナメントが異常となる問題を解決
#318 がベースとなっています（必須）
=> Fix duplication of patching match

frontend/static_vol/js/components/Home.js
42login使用時に自動リフレッシュが適用になっていなかった点を修正
=> Add auto token refresh to 42login

backend/scandamus/players/views.py, backend/scandamus/providers42/views.py, frontend/static_vol/js/components/Home.js
=> Set register transaction atomic

frontend/static_vol/js/modules/websocket.js
故意にサーバーを落とすなどして切断させた場合、クライアントは再接続を試みますが、その際にUncaughtなrejectが発生していたのでロジックを変更
サーバーを停止させた際に以下のようになること。
ちなみに停止後すぐに再起動すれば（サーバー能力に余裕があれば）再接続に間に合うと思います。
間に合わない場合は
```
this.reconnectInterval = 1000; // 再接続の試行間隔
this.maxReconnectAttempts = 10; // 再接続の最大試行回数
```
を調整すれば実験可能です。
=> Server offline logout

backend/scandamus/players/serializers.py
#338 
- ユーザー名を「--------」として表示
- 画像はデフォルトに
=> Handle deleted user

pong-server/game-server/pong/consumers.py
=> FIX: exit before patch match API part2

frontend/static_vol/js/modules/token.js
=> Change refresh interval

.gitignore, backend/scandamus/scandamus/settings.py, backend/tools/docker-entrypoint.sh, frontend/tools/ssl.conf, frontend/tools/test_ssl.conf
- Dockerビルド時に必要なファイルをstaticに収集
=> Admin static files

backend/scandamus/game/match_utils.py
#349 
特定の条件下で発火する例外をハンドリング
admin操作時であり、メンテナンスとして行うために問題とはならないはずだが念のため対応
=> Handle get_player excecption
