- frontend/Dockerfile
- frontend/tools/docker-entrypoint.sh
期待するコンテナの起動順序を確実にするため、waitするように変更
- 変更前では場合によりfrontend （nginx）の起動が先行してしまってbackendやpong-serverの名前解決でコケる可能性がある→nginxの設定読み込み時にエラーとなる
> Ensure container startup sequence

- backend/scandamus/game/match_utils.py
- pong-server/game-server/pong/consumers.py
- pong4-server/game-server/pong4/consumers.py
#113 に対応
player_name（player1やplayer2など）はゲームサーバー上でどのプレイヤーであるかを判断する重要なキーなため、悪意を持ったユーザーがクライアントを書き換えるとplayer2であってもplayer1として申告することにより、ゲームの進行を妨げることが可能だった。
今回の変更はbackend側で生成するJWTに含めることでこの種の攻撃を不可能にする。
> Include player name to JWT

- backend/scandamus/game/consumers.py
- backend/scandamus/game/friend_match.py
- backend/scandamus/game/lounge_match.py
- backend/scandamus/game/match_utils.py
- Playerのstatusがマッチング中の際はwaitingにリセット
- 試合中の場合はそのまま。TODO: 将来のPRで再接続時にstatusを確認し、試合中であってまだ終了していないMatchであればゲーム画面へ遷移：意図しない切断時の救済措置
- フレンドマッチリクエストの最中に切断した場合にpending_requestsから当該要素を削除
migrationの問題を避けるため最新のmainベースとしてリオープンしました
修正内容は同じです
@snara-42  さんご指摘の問題は確認出来ませんでした。問題が起きましたらログなどご提供いただけると大変助かります。
> Handle match request while matching [REOPEN]

- backend/scandamus/players/views.py
- frontend/static_vol/js/components/Home.js
- frontend/static_vol/js/main.js
- frontend/static_vol/js/modules/logout.js
- frontend/static_vol/js/modules/token.js
リロードしたらログアウトするようにしました。
セッションを跨いでtokenを保持する必要がなくなったので、
tokenの保存先をlocalStorageからsessionStorageに変更しています。
---
リロード後に自動ログインしてしまう場合、
localStorageにtokenが残っていると思われます。
お手数ですが手動で削除お願いします🙏
---
https://github.com/scandamus/ft_transcendence/issues/79
なぜかログインしていることになってしまう不具合については
以前のセッションでlocalStorageに保持されたtokenの扱いが適切ではなかったためと推測されるので、
このPRの変更によって改善されるはずです
> reloadしたらLogOut

- backend/scandamus/game/consumers.py
- backend/scandamus/game/friends.py
- backend/scandamus/players/serializers.py
- backend/scandamus/players/urls.py
- backend/scandamus/players/views.py
- frontend/static_vol/css/style.css
- frontend/static_vol/js/components/Friends.js
- frontend/static_vol/js/components/PageBase.js
- frontend/static_vol/js/modules/friendList.js
- frontend/static_vol/js/modules/friendListener.js
- frontend/static_vol/js/modules/friendsApi.js
- frontend/static_vol/js/modules/friendsRequest.js
- frontend/static_vol/js/modules/gameApi.js
- frontend/static_vol/js/modules/gameList.js
- frontend/static_vol/js/modules/labels_ar.js
- frontend/static_vol/js/modules/labels_en.js
- frontend/static_vol/js/modules/labels_fr.js
- frontend/static_vol/js/modules/labels_he.js
- frontend/static_vol/js/modules/labels_ja.js
- frontend/static_vol/js/modules/labels_la.js
(#164 からの仕切り直しです)
`/friends` ページ、 recommendedリストが表示されるようにしました。
- 対象者は最近のmatch30件で対戦したplayer
(※古すぎるMatch結果から勧められても覚えていないでしょうし、新しい方から件数で対象者を絞ることにしました)
- 上記から、friend, friendリクエスト送信済みのユーザーを除外した上で5人、ランダムに表示
- 対象者のいない場合、`no recommended player`メッセージ表記
- friend requestを送信するとリストから消えます。5人とも消えると`no recommended player`メッセージ表記
- 5人とも消えたら再取得してリスト更新することも考えましたが、対象者全てにFriend申請し尽くすことを続けていくと
常に対象者が枯渇しそうですし、アクセスごとに5人ずつ小出しにしていくことにしました
> [friend]recommendedからの友達申請

- pong-server/game-server/pong/consumers.py
- pong4-server/game-server/pong4/consumers.py
- master以外がdisconnectしたときにもcreate_taskしてしまっていたので、内部的なところははわかりません(考えていない)が2倍処理が行われてしまっていました
- 実装的には、scheduled_taskがNoneではないプレーヤーがdisconnectされたときのみcreate_taskをもう一度行います
- master以外のプレーヤーを切断してみてスピードがかわっていないかテストしていただけると
> [update]masterを再決定する処理はmasterがdisconnectされたのがmasterのときのみ

- pong-server/game-server/pong/consumers.py
左右のパドルを同時に操作すると干渉してしまう問題を解消
これまで複数デバイスで操作しなかったために顕在化しなかった致命的なバグでした
backendとpong-serverのsettings.pyにあるALLOWED_HOSTSに、サーバーを稼働しているIPを追加
URLをそのIPで指定して複数デバイスからログインしてゲームで同時にキー操作を行う（このPR以前と比較してみてください）
> Resolve conflicts with left and right paddles

- backend/scandamus/players/models.py
- backend/scandamus/players/views.py
すみません！
avatrtのリサイズがPlayer更新時に実行されていました。
Avatar uploadのタイミングで実行されるように修正しました。
なぜか発生するavatar差分、このせいでした。陳謝🙇
https://github.com/scandamus/ft_transcendence/issues/213 こちらのアバターの不整合は別の原因のため改善しておらずです。
> [fix]avatar save timing

- backend/scandamus/game/friends.py
- frontend/static_vol/js/modules/labels_ar.js
- frontend/static_vol/js/modules/labels_en.js
- frontend/static_vol/js/modules/labels_fr.js
- frontend/static_vol/js/modules/labels_he.js
- frontend/static_vol/js/modules/labels_ja.js
- frontend/static_vol/js/modules/labels_la.js
- frontend/static_vol/js/modules/websocketHandler.js
https://github.com/scandamus/ft_transcendence/issues/191 
>お互いに送りあった状態でフレンドリクエストが表示されている＆＆他方がAccept＆＆自身がさらにAcceptすると
>Error: Invalid request idになる
この挙動について、フレンドリクエストの送信時点でリクエストを作成しないようにしました
（バー通知で理由を表示）
- フレンドリクエストを受け取り済みの相手に、逆にリクエストを送ろうとした
- フレンドリクエスト送信済みの相手に重ねてリクエストを送ろうとした
> friendRequestがダブる場合のハンドリング

- frontend/static_vol/js/modules/modal.js
トーナメントへのentry入力中にフレンドマッチを受け取ると、割り込みで受信できてしまっていました。
プレイヤーが意図して行なっているタスクを優先してトーナメントエントリー中は割り込ませず、
rejectを送信元に送ってキャンセルさせるようにしました
https://github.com/scandamus/ft_transcendence/issues/69
> [fix]トーナメントエントリー入力中のフレンドマッチ申請をreject

- backend/scandamus/game/tasks.py
- frontend/static_vol/js/modules/tournament.js
#272 
- トーナメント控室移動を開始30秒前に変更
- その時点でエントリーしているプレイヤーがマッチ中の場合は強制的にExit（handleExitGameを呼ぶ）
現状のhandleExitGameの実装により、単純にそのゲームを破棄して控室に移動するだけで、マッチ自体は継続（相手の1人プレーになる）。別のPRで-1となることを期待しています。
> Exit match for tournament

- backend/scandamus/game/models.py
#294 
トーナメントで一方のプレイヤーが現れなかった場合、そのプレイヤーは-1、他のプレイヤーは0となりますが、winner決定ロジックがpong4も対象しているためにplayer3、4の0をカウントしてしまうことによりplayer1を誤って勝者となっていたバグを修正
> Fix set_winner condition

- frontend/static_vol/js/components/GamePlay.js
- frontend/static_vol/js/components/GamePlayQuad.js
タイトルのエラーを直しました。
webソケットのクローズのタイミングを画面遷移前に修正しました。
手元ではトーナメントも正常に開始、終了できました。
> ゲーム終了直後にキー操作を送ろうとしてエラーが発生する

- frontend/static_vol/js/components/Tournament.js
upcomingなトーナメントが読み込まれるとstart_datesが設定されるが、トーナメントが実行されても値が保持されるために以降の設定時にも不本意なバリデーションがかかってしまう問題を解消。
併せてCustomValidityを毎回クリアするように変更。
> Update tournament create starttime handling

- frontend/static_vol/js/components/Home.js
#316 
- バリデーションにひっかかってそれ以上動かなくなる状態を解消
1. ユーザー名に2文字のみを入れるなどフロントのバリデーションにひっかかるようにしてログインボタンを押す
2. 有効なユーザー名とパスワードを入力して正常にログインできることを確認
> Reset login progress flag

- backend/scandamus/game/management/commands/gen_dummy_match.py
ダミーのマッチデータ作成時にwinnerがセットされない問題を修正（api-internal経由以外ではupdateが発火しない）
以下の点について考慮すべき
- 現状では同点の際にwinnerがNoneになる（トーナメントのみ決定するロジックなので）
- pong4の得点があり得ない点数になっている
> Fix dummy match data

- backend/scandamus/players/serializers.py
DashboardのmatchLog、自分のwinマークがつかなくなっていました。
復活させました
> [fix]matchLogに自分のwinマークがつかなくなっていた

- frontend/static_vol/js/components/Dashboard.js
- frontend/static_vol/js/modules/labels_en.js
- frontend/static_vol/js/modules/labels_fr.js
- frontend/static_vol/js/modules/labels_ja.js
- frontend/static_vol/js/modules/switchLanguage.js
avatarのuploadでエラーが返ってきたら強制ログアウトにしていたのですが、
token errorの場合のみログアウトさせるようにしました。
`415 Unsupported Media Type`やbad requestなどでも強制ログアウトがかかっていたのですが、これはログインしたままでも良さそうに思ったため。
> [fix]avatar upload error 415は強制ログアウトさせない

- backend/scandamus/game/consumers.py
- backend/scandamus/scandamus/api_exception.py
- backend/scandamus/scandamus/settings.py
- docker-compose.yml
- docker-compose_test.yml
- frontend/tools/ssl.conf
- frontend/tools/test_ssl.conf
- pong-server/game-server/mysite/settings.py
- pong4-server/game-server/mysite/settings.py
#288 
#322 
- REST API用に例外ハンドラーを設定
- DEBUG=Falseにした場合にクライアントにデバッグ情報が渡らないようにした
- DEBUG=Falseではavatarファイルにアクセス出来ないため、ディレクトリをfrontendにマウントしてnginxからアクセスさせるよう変更
- Null userの切断時に例外が飛ばないように変更
https://localhost/api/game/match/1/
→404
https://localhost/api/players/recommend/
→401 {"message":"Authentication credentials were not provided."}
セキュリティ的に問題のない最低限のエラー内容を返しています
> API error handling

- frontend/static_vol/js/main.js
```
<select id="languageSelect">
<option value="end" lang="en">English</option>
<option value="<script>alert(0)</script>" lang="ja">日本語</option>
<option value="fr" lang="fr" selected="selected">français</option>
</select>
```
とかされるとhtmlのlang属性に`<script>alert(0)</script>`や`end`が入ったりしてしまうので阻止します
> [fix]選択言語が想定外なら即return

- frontend/static_vol/js/components/Home.js
42loginボタンを連打できるようになっていて、
1ブラウザで複数ログインによる掃き出しなど起こっていました。
通常のログインボタン同様、連打を防止するようにしました。
> [fix]42logingボタンの連打を防止
